spring:
  application:
    name: bizu-portal

  datasource:
    url: jdbc:postgresql://localhost:5432/bizu_db
    username: bizu_user
    password: bizu_password
    driver-class-name: org.postgresql.Driver

  flyway:
    validate-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/auth/realms/bizu-portal}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      repositories:
        enabled: false

  mail:
    host: smtp.hostinger.com
    port: 465
    username: ${MAIL_USERNAME:noreply@mjolnix.com.br}
    password: ${MAIL_PASSWORD:P3dr0l3m02#@1}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

axon:
  mail:
    from-address: ${MAIL_USERNAME:noreply@mjolnix.com.br}
    from-name: "Axon Academy"

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.bizu.portal: INFO
